// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okptuqgnyvfpyfxhrvhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rcHR1cWdueXZmcHlmeGhydmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNTY5NDcsImV4cCI6MjA2NDkzMjk0N30.sTO1gCPiRY9PKIxdKn6sxiDg-a6sX7820KE5FblYoIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);